name: Automation 🤖

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request_target:

jobs:
  compose-comment:
    name: Compose PR comment
    if: ${{ always() && !cancelled() && github.event_name == 'pull_request_target' }}
    uses: ./.github/workflows/job_messages.yml
    with:
      commit: ${{ github.event.pull_request.head.sha }}
      commenting_workflow_run_id: ${{ github.run_id }}
      in_progress: true

  push-comment:
    name: Push comment to PR 🖥️
    if: ${{ always() && !cancelled() && github.event_name == 'pull_request_target' && needs.compose-comment.result == 'success' }}
    runs-on: ubuntu-latest
    needs:
      - compose-comment

    steps:
      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ needs.compose-comment.outputs.msg }}
          comment_tag: ${{ needs.compose-comment.outputs.marker }}

  project:
    name: Project board 📊
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Ongoing development
          column: In progress
          repo-token: ${{ secrets.JF_BOT_TOKEN }}

  label:
    name: Labeling 🏷️
    if: ${{ always() && !cancelled() }}
    runs-on: ubuntu-latest

    steps:
      - name: Label PR depending on modified files
        uses: actions/labeler@v5.0.0
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true
        with:
          repo-token: "${{ secrets.JF_BOT_TOKEN }}"

      - name: Check all PRs for merge conflicts ⛔
        uses: eps1lon/actions-label-merge-conflict@v3.0.2
        with:
          dirtyLabel: "merge conflict"
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
