name: Release 🌍

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref }}
  cancel-in-progress: true

on:
  release:
    types:
      - released
      - prereleased
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  main:
    name: ${{ github.event_name == 'push' && 'Unstable 🚀⚠️' || 'Stable 🏷️✅' }}
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      commit: ${{ github.event_name == 'push' && github.sha }}
      is_prerelease: ${{ github.event_name == 'release' && github.event.action == 'prereleased' }}
      tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name }}
      push: true
